language: go

branches:
  except:
    - gh-pages

before_install:
  - ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod 600 ~/.ssh/authorized_keys
  - sudo apt-get -y install python-virtualenv
  - git clone https://github.com/ceph/ceph-deploy
  - cd ceph-deploy
  - ./bootstrap
  - ./ceph-deploy install --release firefly `hostname`
  - ./ceph-deploy pkg --install librados-dev `hostname`

install:
  - echo "asdf"

script: "exit 0"

notifications:
  recipients:
    - noahwatkins@gmail.com
  email:
    on_success: always
    on_failure: always
